server:
  port: 8000
consentmanager:
  consentservice:
    defaultPageSize: ${DEFAULT_PAGE_SIZE}
    maxPageSize: ${MAX_PAGE_SIZE}
    url: ${CONSENT_SERVICE_URL}
    purposeOfUseDefUrl: classpath:/static/ValueSet/purpose-of-use.json
    hiTypesDefUrl: classpath:/static/ValueSet/health-info-type.json
    #in minutes
    consentRequestExpiry: ${CONSENT_REQUEST_EXPIRY}
  scheduler:
    consentExpiryCronExpr: ${CONSENT_EXPIRY_CRON_EXPRESSION}
    consentRequestExpiryCronExpr: ${CONSENT_REQUEST_EXPIRY_CRON_EXPRESSION}
  clientregistry:
    url: ${Client_Registry_Url}
  gatewayservice:
    baseUrl: ${GATEWAY_BASE_URL}
    requestTimeout: ${GATEWAY_REQUEST_TIMEOUT}
    enabled: ${GATEWAY_ENABLED}
    clientSecret: ${GATEWAY_CLIENT_SECRET}
    clientId: ${GATEWAY_CLIENT_ID}
    jwkUrl: ${CENTRAL_REGISTRY_JWK_URL}
  userservice:
    url: ${User_Service_Url}
    transactionPinDigitSize: ${TRANSACTION_PIN_DIGIT_SIZE}
    transactionPinTokenValidity: ${TRANSACTION_PIN_TOKEN_VALIDITY}
    userCreationTokenValidity: ${USER_CREATION_TOKEN_VALIDITY}
    userIdSuffix: ${USER_ID_SUFFIX}
    maxOtpAttempts: ${MAX_OTP_ATTEMPTS}
    maxOtpAttemptsPeriodInMin: ${MAX_OTP_ATTEMPTS_PERIOD_IN_MIN}
    otpAttemptsBlockPeriodInMin: ${OTP_ATTEMPTS_BLOCK_PERIOD_IN_MIN}
    maxIncorrectPinAttempts: 5
    otpInvalidAttemptsBlockPeriodInMin: ${OTP_INVALID_ATTEMPT_BLOCK_PERIOD_IN_MIN}
    otpMaxInvalidAttempts: ${MAX_INVALID_OTP_ATTEMPTS}
  lockeduserservice:
    maximumInvalidAttempts: ${MAXIMUM_INVALID_ATTEMPTS}
    coolOfPeriod: ${COOL_OF_PERIOD}
  otpservice:
    url: ${Otp_Service_Url}
    identifiers:
      - MOBILE
    expiryInMinutes: ${OTP_EXPIRY_IN_MINUTES}
  jwt:
    secret: ${JWT_SECRET}
  keycloak:
    baseUrl: ${KEY_CLOAK_URL}
    clientId: ${KEY_CLOAK_CONSENT_CLIENT_ID}
    clientSecret: ${KEY_CLOAK_CONSENT_CLIENT_SECRET}
    userName: ${KEY_CLOAK_CONSENT_USER_NAME}
    password: ${KEY_CLOAK_CONSENT_PASSWORD}
    jwkUrl:  ${KEY_CLOAK_JWK_URL}
    issuer: ${KEY_CLOAK_TOKEN_ISSUER}
  db:
    host: ${POSTGRES_HOST}
    port: ${POSTGRES_PORT:5432}
    schema: ${CONSENT_MANAGER_DB_NAME}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    poolSize: 5
  dataflow:
    consentmanager:
      url: ${CONSENT_MANAGER_URL}
  linkservice:
    url: ${LINK_SERVICE_URL}
    txnTimeout: ${LINK_TRANSACTION_TIMEOUT}
  #Valid values are guava(for local), redis
  cacheMethod: ${CACHE_METHOD:guava}
  redis:
    #Will not be used if cacheMethod is guava
    host: ${REDIS_HOST}
    port: 6379
    password: ${REDIS_PASSWORD}
  listeners:
    maximumRetries: ${LISTENERS_MAXIMUM_RETRIES}
    # In milliseconds
    retryInterval: ${LISTENERS_RETRY_INTERVAL}
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
