server:
  port: 8000
consentmanager:
  consentservice:
    defaultPageSize: ${DEFAULT_PAGE_SIZE}
    maxPageSize: ${MAX_PAGE_SIZE}
    url: ${CONSENT_SERVICE_URL}
  clientregistry:
    XAuthToken: ${Auth_Token}
    clientId: ${CENTRAL_REGISTRY_ID}
    url: ${Client_Registry_Url}
    jwkUrl: ${CENTRAL_REGISTRY_JWK_URL}
  userservice:
    url: ${User_Service_Url}
    transactionPinDigitSize: ${TRANSACTION_PIN_DIGIT_SIZE}
    transactionPinTokenValidity: ${TRANSACTION_PIN_TOKEN_VALIDITY}
    userCreationTokenValidity: ${USER_CREATION_TOKEN_VALIDITY}
    userIdSuffix: ${USER_ID_SUFFIX}
  otpservice:
    url: ${Otp_Service_Url}
    identifiers:
      - MOBILE
  jwt:
    secret: ${JWT_SECRET}
  keycloak:
    baseUrl: ${KEY_CLOAK_URL}
    clientId: ${KEY_CLOAK_CONSENT_CLIENT_ID}
    clientSecret: ${KEY_CLOAK_CONSENT_CLIENT_SECRET}
    userName: ${KEY_CLOAK_CONSENT_USER_NAME}
    password: ${KEY_CLOAK_CONSENT_PASSWORD}
    jwkUrl:  ${KEY_CLOAK_JWK_URL}
    issuer: ${KEY_CLOAK_TOKEN_ISSUER}
  db:
    host: ${POSTGRES_HOST}
    port: 5432
    schema: ${CONSENT_MANAGER_DB_NAME}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    poolSize: 5
  dataflow:
    consentmanager:
      url: ${CONSENT_MANAGER_URL}
  linkservice:
    url: ${LINK_SERVICE_URL}
  cacheMethod: guava
  redis:
    #Will not be used if cacheMethod is guava
    host: localhost
    port: 6380
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
