server:
  port: 8000
hdaf:
  clientregistry:
    XAuthToken: 8e983a1719e20913be6c61e9b552e88fc6032c21e1030f1abda986d17326b2b0
    clientId: 6
    url: http://localhost:8080/api/1.0
  userservice:
    url: http://localhost:8000
  db:
    host: localhost
    port: 5432
    schema: consent_manager
    user: postgres
    password: postgres
    poolSize: 5
