server:
  port: 9000
consentmanager:
  consentservice:
    defaultPageSize: 20
    maxPageSize: 100
    url: http://localhost:9000
    purposeOfUseDefUrl: classpath:/static/ValueSet/purpose-of-use.json
    hiTypesDefUrl: classpath:/static/ValueSet/health-info-type.json
    #in minutes
    consentRequestExpiry: 60
  scheduler:
    consentExpiryCronExpr: '0 0 * ? * *'
    consentRequestExpiryCronExpr: '0 0 0/12 ? * *'
  clientregistry:
    url: http://localhost:8080
  gatewayservice:
    enabled: true
    baseUrl: http://localhost:8004/v0.5
    requestTimeout: 10000
    clientSecret: 2a38856a-61f0-4bbd-9d68-9e5243cdb73a
    clientId: ncg
    jwkUrl: http://localhost:8004/v0.5/certs
  userservice:
    url: http://localhost:9000
    transactionPinDigitSize: 4
    transactionPinTokenValidity: 2
    userCreationTokenValidity: 5
    userIdSuffix: "@ncg"
    maxOtpAttempts: 5
    maxOtpAttemptsPeriodInMin: 10
    otpAttemptsBlockPeriodInMin: 2
    otpInvalidAttemptsBlockPeriodInMin: 2
    otpMaxInvalidAttempts: 5
    maxIncorrectPinAttempts: 5
  lockeduserservice:
    maximumInvalidAttempts: 5
    coolOfPeriod: 8
  otpservice:
    url: http://localhost:5000
    identifiers:
      - MOBILE
    expiryInMinutes: 5
  keycloak:
    baseUrl: http://localhost:9001/auth
    clientId: ncg
    clientSecret: 12d44954-b122-4b53-acbf-7b4c38fa9cf8
    userName: consentmanageruser
    password: user
    jwkUrl: http://localhost:9001/auth/realms/consent-manager/protocol/openid-connect/certs
    issuer: http://localhost:9001/auth/realms/consent-manager
  jwt:
    secret: secret_salt
  db:
    host: localhost
    port: 5432
    schema: consent_manager
    user: postgres
    password: postgres
    poolSize: 5
  dataflow:
    authserver:
      clientId: 1
      clientSecret: NCG_CM
      url: http://localhost:9001
    consentmanager:
      url: http://localhost:9000
  linkservice:
    url: http://localhost:9000
    txnTimeout: 5000
  cacheMethod: guava
  listeners:
    maximumRetries: 3
    retryInterval: 10000
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
